# Generated by Django 3.1.4 on 2020-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_difficultquestion_easyquestion_mediumquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSubjectQues',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=2000)),
                ('complexity', models.CharField(choices=[('S', 'Simple'), ('M', 'Medium'), ('D', 'Difficult')], max_length=30)),
                ('subject', models.CharField(choices=[('C++', 'C++'), ('Java', 'Java'), ('C', 'C')], max_length=30)),
                ('options', models.CharField(max_length=1000)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
